SocialSharer/config/routes.rb
TwitterExample::Application.routes.draw do
  #root to: 'users#index', via: :get
  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'users#login'
  post 'auth/facebook/callback', to: 'users#login'
  # match 'auth/facebook/callback',to: 'users#login', via: [:get, :post]
  get '/linkedin/auth'      => 'linkedin#auth'
  get '/linkedin/callback'  => 'linkedin#callback'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
	get '/instagram/index' => "instagram#index"
	get '/instagram/connect', to: 'instagram#connect'
	get '/instagram/callback', to: 'instagram#callback'
	get '/instagram/logout', to: 'instagram#logout'

  resources :tweets, only: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get 'enter'  => 'home#show'
  root to: "home#homepage"
end

SocialSharer/app/models/user.rb
class User < ActiveRecord::Base
  @message="Posting on my wall"
  def self.koala(auth)
  	
	access_token = auth['token']
	facebook = Koala::Facebook::API.new(access_token)
	facebook.get_object("me?fields=name,picture")
	facebook.put_wall_post(@message)
	#facebook.put_connections("me", "feed", :message => "#{@message}")
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user.save!
    end
  end

  def tweet(tweet)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.config.twitter_key
      config.consumer_secret     = Rails.application.config.twitter_secret
      config.access_token        = oauth_token
      config.access_token_secret = oauth_secret
    end
    
    client.update(tweet)
  end
end

SocialSharer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

SocialSharer/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

SocialSharer/app/controllers/instagram_controller.rb
Instagram.configure do |config|
    config.client_id = "7e4e684ff76144c7ba70df44957b63ea"
    config.client_secret = "9f54ed28341a417e8f2cc3307b61fabf"
end

class InstagramController < ApplicationController

  def index
    @instagram = Instagram.user_recent_media("373882141", {:count => :all})
  end

  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => ENV['https://instagram.com/'])
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => ENV['https://instagram.com/'])
    session[:user_name] = response.user.full_name
    session[:access_token] = response.access_token
    redirect_to "/"
  end

  def logout
    session.clear
    redirect_to '/'
  end

end

SocialSharer/app/controllers/linkedin_controller.rb
class LinkedinController < ApplicationController
 
  def init_client
    key = "77s5fkcdyi8qxn"
    secret = "Vy92d4AvM4OgssFU" 
    linkedin_configuration = { :site => 'https://api.linkedin.com',
        :authorize_path => '/uas/oauth/authenticate',
        :request_token_path =>'/uas/oauth/requestToken?scope=r_basicprofile+r_fullprofile+r_emailaddress+r_network+r_contactinfo',
        :access_token_path => '/uas/oauth/accessToken' }
    @linkedin_client = LinkedIn::Client.new(key, secret,linkedin_configuration )
  end
 
  def auth
    init_client
    request_token = @linkedin_client.request_token(:oauth_callback => "http://#{request.host_with_port}/linkedin/callback")
    session[:rtoken] = request_token.token
    session[:rsecret] = request_token.secret
    redirect_to @linkedin_client.request_token.authorize_url
  end
 
  def callback
    init_client
    if session[:atoken].nil?
      pin = params[:oauth_verifier]
      atoken, asecret =  @linkedin_client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
      session[:atoken] = atoken
      session[:asecret] = asecret
    else
      @linkedin_client.authorize_from_access(session[:atoken], session[:asecret])
    end
 
    c = @linkedin_client
    
    profile_1 = c.profile(:fields=>["first_name","last_name","headline","public_profile_url","date-of-birth","main_address","phone-numbers","primary-twitter-account","twitter-accounts","location"])
 
    puts "profile_1 = #{profile_1}"
 
    profile_2 = c.profile(:fields=>["positions","three_current_positions","three_past_positions","publications","patents"])
 
    puts "profile_2 = #{profile_2}"
 
    profile_3 = c.profile(:fields=>["languages","skills","certifications","educations"])
    
    puts "profile_3 = #{profile_3}"
 
 
    session[:atoken] = nil
    session[:asecret] = nil
    redirect_to root_path(:imported_from_linkedin=>"success")
  end
 
end

SocialSharer/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

SocialSharer/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    current_user.tweet(twitter_params[:message])
  end

  def twitter_params
    params.require(:tweet).permit(:message)
  end
end

SocialSharer/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def login
    @user = User.koala(request.env['omniauth.auth']['credentials'])
  end
  
  def create
   @user[:access_token] = request.env['omniauth.auth']['credentials']['token'] 
   @user[:access_token_secret] = request.env['omniauth.auth']['credentials']['secret']
   redirect_to show_path, notice: 'Signed in'
  end

  def update
  end
end 

SocialSharer/app/helpers/application_helper.rb
module ApplicationHelper
end

SocialSharer/app/helpers/home_helper.rb
module HomeHelper
end

SocialSharer/app/helpers/sessions_helper.rb
module SessionsHelper
end

SocialSharer/app/helpers/tweets_helper.rb
module TweetsHelper
end

SocialSharer/app/views/home/homepage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Social Sharer</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css.scss.erb" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <li>
                        <%= link_to "Sign in with Facebook", '/auth/facebook' %>
                    </li>
                    <li>
			
    <%= link_to "Send a Tweet", new_tweet_path %>
                    </li>
                    <li>
			<%= link_to "Instagram Feed", "/instagram/index" %>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>#SocialSharer</h1>
                <hr>
                <p>Share your Thoughts and Memories!</p>
                <%= link_to "LET'S GET STARTED", 'enter' %>
                
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Social Sharer shares your memories on multiple social media!</p>
                    <a href="#" class="btn btn-default btn-xl">Get Started!</a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark" id="contact">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Contact Us</h2>
                    <p class="text-faded">E-mail: socialsharertues@gmail.com</p>
                    <h3>Developers</h3>
                    <p class="text-faded">Atanaska Ivancheva</p>
                    <p class="text-faded">Lili Kokalova</p>
                    <p class="text-faded">Stefan Radev</p>
            </div>
        </div>
    </aside>


    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

</body>

</html>

SocialSharer/app/views/home/show.html.erb
<div>
<% if current_user %>
Signed in as <strong><%= current_user.name %></strong>!
<%= link_to "Sign out", signout_path, id: "sign_out" %>
<% else %>
<%= link_to "Sign in with Twitter", "/auth/twitter", id: "sign_in" %>
<% end %>
</br>
<%= link_to "Sign in with Facebook", '/auth/facebook' %>
</br>
<%= link_to "Instagram Feed", "/instagram/index" %>

</div>

<% if !current_user.nil? %>
    <p>Click The link below to send a tweet.</p>
    <%= link_to "Send a Tweet", new_tweet_path %>
<% else %>
    <p>You must log in first.</p>
<% end %>

SocialSharer/app/views/instagram/index.html.erb
<% @instagram.each do |instagram| %>

    <%= image_tag instagram.images.standard_resolution.url %>

    <% end %>

SocialSharer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Sharer</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
    <%= yield %>
    
  </body>
</html>

SocialSharer/app/views/users/index.html.erb
<%= link_to "Facebook Login", '/auth/facebook' %>
<%= link_to "Twitter Login", '/auth/twitter' %> 
<%= link_to "Instagram Feed", "/instagram/index" %>

SocialSharer/app/views/users/login.html.erb
<p>
  <%= form_for :koala,url: auth_facebook_callback_path,method: :post do |f| %>
    <%= f.text_field @message %><br />
    <%= f.submit "Post!" %>
  <% end %>
</p>

SocialSharer/app/views/users/update.html.erb
<p>hiiiiii</p> 